package com.drp.freechat.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.drp.freechat.entity.SmsConversations;

import com.drp.freechat.greendao.SmsConversationsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig smsConversationsDaoConfig;

    private final SmsConversationsDao smsConversationsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        smsConversationsDaoConfig = daoConfigMap.get(SmsConversationsDao.class).clone();
        smsConversationsDaoConfig.initIdentityScope(type);

        smsConversationsDao = new SmsConversationsDao(smsConversationsDaoConfig, this);

        registerDao(SmsConversations.class, smsConversationsDao);
    }
    
    public void clear() {
        smsConversationsDaoConfig.clearIdentityScope();
    }

    public SmsConversationsDao getSmsConversationsDao() {
        return smsConversationsDao;
    }

}
