package com.drp.freechat.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.drp.freechat.entity.SmsConversations;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SMS_CONVERSATIONS".
*/
public class SmsConversationsDao extends AbstractDao<SmsConversations, Long> {

    public static final String TABLENAME = "SMS_CONVERSATIONS";

    /**
     * Properties of entity SmsConversations.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Type = new Property(1, int.class, "type", false, "TYPE");
        public final static Property Status = new Property(2, int.class, "status", false, "STATUS");
        public final static Property Date = new Property(3, long.class, "date", false, "DATE");
        public final static Property Body = new Property(4, String.class, "body", false, "BODY");
    }


    public SmsConversationsDao(DaoConfig config) {
        super(config);
    }
    
    public SmsConversationsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SMS_CONVERSATIONS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TYPE\" INTEGER NOT NULL ," + // 1: type
                "\"STATUS\" INTEGER NOT NULL ," + // 2: status
                "\"DATE\" INTEGER NOT NULL ," + // 3: date
                "\"BODY\" TEXT);"); // 4: body
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SMS_CONVERSATIONS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SmsConversations entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getType());
        stmt.bindLong(3, entity.getStatus());
        stmt.bindLong(4, entity.getDate());
 
        String body = entity.getBody();
        if (body != null) {
            stmt.bindString(5, body);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SmsConversations entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getType());
        stmt.bindLong(3, entity.getStatus());
        stmt.bindLong(4, entity.getDate());
 
        String body = entity.getBody();
        if (body != null) {
            stmt.bindString(5, body);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SmsConversations readEntity(Cursor cursor, int offset) {
        SmsConversations entity = new SmsConversations( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // type
            cursor.getInt(offset + 2), // status
            cursor.getLong(offset + 3), // date
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // body
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SmsConversations entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setType(cursor.getInt(offset + 1));
        entity.setStatus(cursor.getInt(offset + 2));
        entity.setDate(cursor.getLong(offset + 3));
        entity.setBody(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SmsConversations entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SmsConversations entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SmsConversations entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
